Enh/allow impersonate
humhub/rest pull request #117
Opened 2023-04-16 19:16 UTC by gevorgmansuryan

2023-04-17 09:45 UTC, luke- requested changes
@gevorgmansuryan ~~Does the PR include other commits? Can you please check again? Would be great to have only the Impersonate Commits to review.~~ Got it, I'll merge the BearerAuth PR first.

2023-04-17 16:09 UTC, gevorgmansuryan commented
> @gevorgmansuryan Can you please try to `rebase` this PR so it only contains Commits regarding the Impersonate?

done

2023-04-17 18:06 UTC, luke- requested changes
@gevorgmansuryan Thanks looks good. Two points:
- Can you please enhance the tests a bit
- Are expired tokens somewhere deleted? Maybe this could be done when inserting a new token..

2023-04-19 12:53 UTC, luke- approved these changes

2023-04-19 12:54 UTC, merged